-- Set comment to schema: "public"
COMMENT ON SCHEMA "public" IS 'RefURL application schema';
-- Create "configs" table
CREATE TABLE "public"."configs" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "CONFIG_NAME" character varying(255) NOT NULL, "CONFIG_VALUE" character varying(255) NOT NULL, PRIMARY KEY ("id"));
-- Create index "idx_config_name" to table: "configs"
CREATE UNIQUE INDEX "idx_config_name" ON "public"."configs" ("CONFIG_NAME");
-- Create "users" table
CREATE TABLE "public"."users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "email" character varying(255) NOT NULL, "name" character varying(255) NOT NULL, "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY ("id"));
-- Create index "idx_email" to table: "users"
CREATE UNIQUE INDEX "idx_email" ON "public"."users" ("email");
-- Create "urls" table
CREATE TABLE "public"."urls" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "owner" bigint NULL, "original_url" text NOT NULL, "short_code" character varying(10) NOT NULL, "title" character varying(255) NULL, "clicks" bigint NOT NULL DEFAULT 0, "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, "clicks_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY ("id"), CONSTRAINT "fk_user" FOREIGN KEY ("owner") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create index "idx_short_code" to table: "urls"
CREATE UNIQUE INDEX "idx_short_code" ON "public"."urls" ("short_code");
